In [9]:
import numpy as np

def magic_square_upright():
    n = int(input("Enter the size of matrix : "))
    arr1 = [[0 for x in range(n)] for y in range(n)]
    arr = np.array(arr1)
    i = 0
    j = n//2
    arr[i,j] = 1
    constant = int(n*(n**2 + 1)/2)
    
    for k in range(2,n*n+1):
        i-=1
        j+=1
        if(j == n):
            j = 0
        elif(i == -1):
            i = n-1
        if((i==-1 and j==n) or (arr[i,j] != 0)):
            i+=2
            j-=1
        arr[i,j] = k
    print("Constant value : ",constant,"\n")
    print(arr)

magic_square_upright()
   

Enter the size of matrix : 7
Constant value :  175 

[[30 39 48  1 10 19 28]
 [38 47  7  9 18 27 29]
 [46  6  8 17 26 35 37]
 [ 5 14 16 25 34 36 45]
 [13 15 24 33 42 44  4]
 [21 23 32 41 43  3 12]
 [22 31 40 49  2 11 20]]
